import 'dart:ffi';
import 'dart:io';
import 'package:ffi/ffi.dart';

import 'ffi/ort_bindings.dart';
import 'dart_onnx_exception.dart';

/// Internal singleton that holds the ONNX Runtime API pointer and dynamic library.
///
/// This class manages the lifecycle of loading the ONNX Runtime shared library
/// and obtaining the OrtApi struct pointer. All high-level classes use this
/// internally to call ORT C API functions.
class OrtFFI {
  static OrtFFI? _instance;

  /// The raw FFI bindings class generated by ffigen.
  final OrtBindings bindings;

  /// The OrtApi struct containing all function pointers.
  final Pointer<OrtApi> api;

  OrtFFI._(this.bindings, this.api);

  /// Get the singleton instance, loading the library if necessary.
  static OrtFFI get instance {
    if (_instance == null) {
      final lib = _loadOrtLibrary();
      final bindings = OrtBindings(lib);
      final apiBase = bindings.OrtGetApiBase();
      final getApi = apiBase.ref.GetApi
          .asFunction<Pointer<OrtApi> Function(int)>();
      final api = getApi(ORT_API_VERSION);
      if (api == nullptr) {
        throw DartONNXException(
          'Failed to get ORT API version $ORT_API_VERSION. '
          'The ONNX Runtime library may be too old.',
        );
      }
      _instance = OrtFFI._(bindings, api);
    }
    return _instance!;
  }

  /// Check the OrtStatus returned from an API call and throw on error.
  void checkStatus(Pointer<OrtStatus> status) {
    if (status == nullptr) return; // success
    final getErrorCode = api.ref.GetErrorCode
        .asFunction<int Function(Pointer<OrtStatus>)>();
    final getErrorMessage = api.ref.GetErrorMessage
        .asFunction<Pointer<Char> Function(Pointer<OrtStatus>)>();
    final releaseStatus = api.ref.ReleaseStatus
        .asFunction<void Function(Pointer<OrtStatus>)>();

    final code = getErrorCode(status);
    final msgPtr = getErrorMessage(status);
    final message = msgPtr.cast<Utf8>().toDartString();
    releaseStatus(status);
    throw DartONNXException(message, errorCode: code);
  }

  // Library loading
  static DynamicLibrary _loadOrtLibrary() {
    // Try custom environment variable first
    final customPath = Platform.environment['DART_ONNX_LIB_PATH'];
    if (customPath != null) {
      return DynamicLibrary.open(customPath);
    }

    if (Platform.isMacOS) {
      try {
        return DynamicLibrary.open('libonnxruntime.dylib');
      } catch (_) {
        // Fallback for macOS Homebrew installations on Apple Silicon
        try {
          return DynamicLibrary.open('/opt/homebrew/lib/libonnxruntime.dylib');
        } catch (_) {
          // Fallback for macOS Homebrew installations on Intel
          return DynamicLibrary.open('/usr/local/lib/libonnxruntime.dylib');
        }
      }
    } else if (Platform.isIOS) {
      return DynamicLibrary.open('libonnxruntime.dylib');
    } else if (Platform.isLinux) {
      return DynamicLibrary.open('libonnxruntime.so');
    } else if (Platform.isWindows) {
      return DynamicLibrary.open('onnxruntime.dll');
    } else if (Platform.isAndroid) {
      return DynamicLibrary.open('libonnxruntime.so');
    } else {
      throw DartONNXException(
        'Unsupported platform: ${Platform.operatingSystem}',
      );
    }
  }
}
